//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbServiceProviderAppEntities : DbContext
    {
        public DbServiceProviderAppEntities()
            : base("name=DbServiceProviderAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<order_header> order_header { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<service_provider> service_provider { get; set; }
        public virtual DbSet<sow_user> sow_user { get; set; }
        public virtual DbSet<sow_user_delivery_address> sow_user_delivery_address { get; set; }
        public virtual DbSet<order_item_report> order_item_report { get; set; }
        public virtual DbSet<order_item_report_appendix> order_item_report_appendix { get; set; }
        public virtual DbSet<spa_changes> spa_changes { get; set; }
        public virtual DbSet<spa_log_in> spa_log_in { get; set; }
        public virtual DbSet<spa_synctimes> spa_synctimes { get; set; }
    }
}
