//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_header()
        {
            this.order_detail = new HashSet<order_detail>();
            this.order_item = new HashSet<order_item>();
        }
    
        public long Id { get; set; }
        public int sow_user_id { get; set; }
        public double total { get; set; }
        public double subtotal { get; set; }
        public double subtotal_ex_tax { get; set; }
        public double tax { get; set; }
        public string orderpayment_type { get; set; }
        public string currency_code { get; set; }
        public string ip_address { get; set; }
        public string customer_note { get; set; }
        public int order_state_id { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual sow_user sow_user { get; set; }
        public virtual order_state order_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
    }
}
