//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_item_report()
        {
            this.order_item_report_appendix = new HashSet<order_item_report_appendix>();
        }
    
        public int Id { get; set; }
        public int order_item_id { get; set; }
        public string comment { get; set; }
        public System.DateTime createdat { get; set; }
        public Nullable<System.DateTime> deletedat { get; set; }
    
        public virtual order_item order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item_report_appendix> order_item_report_appendix { get; set; }
    }
}
