//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_provider_login
    {
        public int Id { get; set; }
        public int service_provider_id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime registeredAt { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        public virtual service_provider service_provider { get; set; }
    }
}
