//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int Id { get; set; }
        public int product_source_id { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string intro_text { get; set; }
        public int category_id { get; set; }
        public int service_provider_id { get; set; }
        public string tax_type { get; set; }
        public int amount_of_bookable_units { get; set; }
        public double price_incl_tax { get; set; }
        public Nullable<double> all_inclusive_extra_charge { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
        public string service_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual service_provider service_provider { get; set; }
    }
}
