//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_Datahandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_customer_comment
    {
        public int Id { get; set; }
        public int product_source_id { get; set; }
        public int sow_user_id { get; set; }
        public string text { get; set; }
        public Nullable<int> stars { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        public virtual sow_user sow_user { get; set; }
    }
}
